package key

import ()

const (
	ADDRESS         = "address"
	APPEND          = "append"
	ARGS            = "args"
	CHUNK_SIZE      = "chunk_size"
	CORS            = "cors"
	DEBUG           = "debug"
	DEFAULT_TYPE    = "default_type"
	DIRECTORY       = "directory"
	ENABLE          = "enable"
	FILE            = "file"
	FLAG            = "flag"
	HANDLER         = "handler"
	HTTP            = "http"
	ID              = "id"
	INCLUDE         = "include"
	LICENSE         = "license"
	LISTEN          = "listen"
	LOCATION        = "location"
	LOG             = "log"
	MAX_FAILS       = "max_fails"
	MAX_FRAMES      = "max_frames"
	MAX_SIZE        = "max_size"
	MAX_TIME        = "max_time"
	METHOD          = "method"
	MODE            = "mode"
	NAME            = "name"
	NOTIFY          = "notify"
	ON_CONNECT      = "on_connect"
	ON_DISCONNECT   = "on_disconnect"
	ON_PLAY         = "on_play"
	ON_PLAY_DONE    = "on_play_done"
	ON_PUBLISH      = "on_publish"
	ON_PUBLISH_DONE = "on_publish_done"
	ON_RECORD       = "on_record"
	ON_RECORD_DONE  = "on_record_done"
	PATTERN         = "pattern"
	PORT            = "port"
	PROTOCOL        = "protocol"
	PROXY           = "proxy"
	RECODER         = "recorder"
	ROOT            = "root"
	RTMP            = "rtmp"
	SERVER          = "server"
	SERVER_NAME     = "server_name"
	TARGET          = "target"
	TIMEOUT         = "timeout"
	UNIQUE          = "unique"
	UPSTREAM        = "upstream"
	URL             = "url"
	WEIGHT          = "weight"
)
